version: "2"
services:
 node:
  build: ../pepinillo-backoffice
  volumes:
   - ../pepinillo-backoffice:/app
  ports:
   - "3000:3000"
  tty: true
  environment:
   - DEBUG=true 
 web:
  build: ../pepinillo-web
  ports:
   - "8088:80"
  volumes:
   - ../pepinillo-web/app:/app
  tty: true
  environment:
   - PORT=80
